"""Strict Tool Calling boundary for UT-Agent model-generated structures."""

from __future__ import annotations

import json
import re
from dataclasses import dataclass
from typing import Any, Generic, TypeVar

from pydantic import BaseModel, ConfigDict, ValidationError

from ut_agent.model_failover import ModelAttempt

OutputT = TypeVar("OutputT", bound=BaseModel)

_SECRET_ASSIGNMENT_RE = re.compile(
    r"(?i)\b(api[_-]?key|token|password|secret|authorization)\b\s*(?:=\s*|:\s+)[^\s,;]+"
)
_MAX_ERROR_LENGTH = 240


class StrictOutputModel(BaseModel):
    """Base class for structures generated by a model."""

    model_config = ConfigDict(strict=True, extra="forbid", str_strip_whitespace=True)


@dataclass(frozen=True)
class StructuredOutputOutcome(Generic[OutputT]):
    """Validated model value together with bounded transport metadata."""

    value: OutputT | None
    model: str
    attempts: tuple[ModelAttempt, ...]
    terminal_error: str = ""
    validation_error: str = ""


def _bounded_error(value: object) -> str:
    text = " ".join(str(value or "").split())
    if not text:
        return ""
    text = _SECRET_ASSIGNMENT_RE.sub(lambda match: f"{match.group(1)}=[REDACTED]", text)
    return text[:_MAX_ERROR_LENGTH]


def _validation_error_code(error: ValidationError) -> str:
    details = error.errors(include_url=False, include_context=False, include_input=False)
    if not details:
        return "schema_validation_error"
    first = details[0]
    location = ".".join(str(part) for part in first.get("loc") or ()) or "root"
    error_type = str(first.get("type") or "invalid")
    return _bounded_error(f"schema:{location}:{error_type}")


def build_output_tool(
    model: type[OutputT],
    *,
    tool_name: str,
    description: str,
) -> dict[str, Any]:
    """Build one OpenAI function definition from the local source-of-truth model."""
    schema = model.model_json_schema()
    schema["additionalProperties"] = False
    return {
        "type": "function",
        "function": {
            "name": tool_name,
            "description": description[:1000],
            "parameters": schema,
        },
    }


def _message_from_outcome(outcome: Any) -> Any:
    response = getattr(outcome, "response", None)
    if response is None:
        return None
    choices = getattr(response, "choices", None)
    if choices:
        return choices[0].message
    return response


def _tool_calls(message: Any) -> list[Any]:
    if isinstance(message, dict):
        return list(message.get("tool_calls") or ())
    return list(getattr(message, "tool_calls", None) or ())


def _tool_call_parts(tool_call: Any) -> tuple[str, Any]:
    if isinstance(tool_call, dict):
        function = tool_call.get("function") or {}
        name = function.get("name") or tool_call.get("name") or ""
        arguments = function.get("arguments")
        if arguments is None:
            arguments = tool_call.get("args")
        return str(name), arguments
    function = getattr(tool_call, "function", None)
    if function is not None:
        return str(getattr(function, "name", "") or ""), getattr(function, "arguments", None)
    return str(getattr(tool_call, "name", "") or ""), getattr(tool_call, "args", None)


def validate_structured_message(
    message: Any,
    *,
    output_model: type[OutputT],
    tool_name: str,
) -> tuple[OutputT | None, str]:
    """Validate that one response contains exactly one well-formed target call."""
    calls = _tool_calls(message)
    if not calls:
        return None, "tool_call_missing"
    if len(calls) != 1:
        return None, "tool_call_count"
    actual_name, arguments = _tool_call_parts(calls[0])
    if actual_name != tool_name:
        return None, _bounded_error(f"tool_name:{actual_name or 'missing'}")
    try:
        if isinstance(arguments, str):
            value = output_model.model_validate_json(arguments)
        elif isinstance(arguments, dict):
            value = output_model.model_validate(arguments)
        else:
            return None, "tool_arguments:not_object"
    except ValidationError as error:
        return None, _validation_error_code(error)
    except (TypeError, ValueError, json.JSONDecodeError):
        return None, "tool_arguments:invalid_json"
    return value, ""


async def call_structured_output(
    system: str,
    user: str,
    *,
    output_model: type[OutputT],
    tool_name: str,
    tool_description: str,
    llm_call=None,
    temperature: float = 0.0,
    model: str | None = None,
    active_model: str | None = None,
    max_tokens: int = 1800,
) -> StructuredOutputOutcome[OutputT]:
    """Call one forced tool and validate its arguments locally."""
    if llm_call is None:
        from ut_agent.llm import call_tool_llm_outcome

        llm_call = call_tool_llm_outcome
    tool = build_output_tool(output_model, tool_name=tool_name, description=tool_description)
    outcome = await llm_call(
        system,
        user,
        tools=[tool],
        tool_choice={"type": "function", "function": {"name": tool_name}},
        temperature=temperature,
        model=model,
        active_model=active_model,
        max_tokens=max_tokens,
    )
    attempts = tuple(getattr(outcome, "attempts", ()) or ())
    selected_model = str(getattr(outcome, "model", "") or "")
    terminal_error = _bounded_error(getattr(outcome, "terminal_error", ""))
    if terminal_error:
        return StructuredOutputOutcome(None, selected_model, attempts, terminal_error=terminal_error)
    value, validation_error = validate_structured_message(
        _message_from_outcome(outcome),
        output_model=output_model,
        tool_name=tool_name,
    )
    return StructuredOutputOutcome(
        value,
        selected_model,
        attempts,
        validation_error=_bounded_error(validation_error),
    )
